language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - sudo rm -f /etc/boto.cfg  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657
install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
env:
  global:
    - AWS_ACCESS_KEY_ID=dummy-access-key
    - AWS_SECRET_ACCESS_KEY=dummy-access-key-secret
    - AWS_DEFAULT_REGION=us-east-1
