# Stubs for mpu.datetime (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import datetime
import random

def add_time(datetime_obj: datetime.datetime, days: int = ..., hours: int = ..., minutes: int = ..., seconds: int = ...) -> datetime.datetime: ...
def generate(minimum: datetime.datetime, maximum: datetime.datetime, local_random: random.Random = ...) -> datetime.datetime: ...
